name = "Beziers"
uuid = "d9521d29-258d-41b1-9527-a72f3fe2dc08"
authors = ["Alphonsus Adu-Bredu"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
